Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.define "tomcat" do |tomcat|
    tomcat.vm.box_check_update = false
    tomcat.vm.hostname="tomcat"
     tomcat.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "tomcatstack"
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
  # forward tomcat port to 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
