Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.define "webdev" do |webdev|
    webdev.vm.box_check_update = false
    webdev.vm.hostname="webdev"
     webdev.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "webdevstack"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
