Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.define "java" do |java|
    java.vm.box_check_update = false
    java.vm.hostname="java"
     java.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "javastack"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
