Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.define "python" do |python|
    python.vm.box_check_update = false
    python.vm.hostname="python"
     python.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "pythonstack"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
