Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.define "guibox" do |guibox|
    guibox.vm.box_check_update = false
    guibox.vm.hostname="guibox"
     guibox.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "guiboxstack"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
